version: '3.8'

services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
    - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306

  app:
    build: .
    depends_on:
      - mysqldb
    links:
    - mysqldb
    ports:
      - 3000:3000
    
